"""initial_schema

Revision ID: 9b59da910a6d
Revises: 
Create Date: 2026-05-17 12:37:59.499734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '9b59da910a6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_parent_id'), 'topic', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topic_slug'), 'topic', ['slug'], unique=True)
    op.create_table('wolfram_cache',
    sa.Column('query_hash', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('query_hash')
    )
    op.create_table('wolfram_usage',
    sa.Column('ym', sa.String(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('cached_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ym')
    )
    op.create_table('concept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('proof_md', sa.Text(), nullable=True),
    sa.Column('examples_md', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_concept_embedding', 'concept', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_concept_topic_id'), 'concept', ['topic_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('stem_md', sa.Text(), nullable=False),
    sa.Column('stem_latex', sa.Text(), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('reference_answer_tex', sa.Text(), nullable=True),
    sa.Column('mc_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mc_correct_key', sa.String(), nullable=True),
    sa.Column('ordered_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variables', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('solution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_concept_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('wolfram_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_difficulty', 'question', ['difficulty'], unique=False)
    op.create_index('ix_question_embedding', 'question', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_question_status'), 'question', ['status'], unique=False)
    op.create_index(op.f('ix_question_topic_id'), 'question', ['topic_id'], unique=False)
    op.create_table('study_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal_topic_id', sa.UUID(), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['goal_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_user', 'study_session', ['user_id'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('hints_used', sa.SmallInteger(), nullable=False),
    sa.Column('response_quality', sa.SmallInteger(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['study_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_session', 'attempt', ['session_id'], unique=False)
    op.create_index('ix_attempt_started', 'attempt', ['started_at'], unique=False)
    op.create_index('ix_attempt_user_question', 'attempt', ['user_id', 'question_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('study_session_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_user_last', 'chat_session', ['user_id', 'last_message_at'], unique=False)
    op.create_table('hint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text_md', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'tier')
    )
    op.create_table('srs_card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('easiness', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id')
    )
    op.create_index('ix_srs_due', 'srs_card', ['user_id', 'due_at'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('cited_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_message_session', 'chat_message', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_message_session', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_srs_due', table_name='srs_card')
    op.drop_table('srs_card')
    op.drop_table('hint')
    op.drop_index('ix_chat_user_last', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('ix_attempt_user_question', table_name='attempt')
    op.drop_index('ix_attempt_started', table_name='attempt')
    op.drop_index('ix_attempt_session', table_name='attempt')
    op.drop_table('attempt')
    op.drop_index('ix_session_user', table_name='study_session')
    op.drop_table('study_session')
    op.drop_index(op.f('ix_question_topic_id'), table_name='question')
    op.drop_index(op.f('ix_question_status'), table_name='question')
    op.drop_index('ix_question_embedding', table_name='question', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_question_difficulty', table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_concept_topic_id'), table_name='concept')
    op.drop_index('ix_concept_embedding', table_name='concept', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('concept')
    op.drop_table('wolfram_usage')
    op.drop_table('wolfram_cache')
    op.drop_index(op.f('ix_topic_slug'), table_name='topic')
    op.drop_index(op.f('ix_topic_parent_id'), table_name='topic')
    op.drop_table('topic')
    op.drop_table('app_user')
    # ### end Alembic commands ###
